test: &default

  # Credentials for REST APIs
  client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: live

  # Credentials for Classic APIs
  app_id: APP-0SK00535KP286891S
  username: contact_api1.everestmg.com
  password: NY43859VYAEUWP4Q
  signature: Axw3jMAg8yAPgNNLitT1yaBqgL3zA9VLNIWcOjFtw-oQMQ9-kp0FzE-y
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  mode: live
  username: <%= ENV['PAYPAL_USERNAME'] %>
  password: <%= ENV['PAYPAL_PASSWORD'] %>
  signature: <%= ENV['PAYPAL_SIGNITURE'] %>
  app_id: APP-0SK00535KP286891S
